language: rust
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - (pushd closest && cargo test; popd)
  - (pushd collatz && cargo test; popd)
  - (pushd pricing && cargo test; popd)
  - (pushd translate && cargo test; popd)